[build.environment]
  NODE_VERSION = "18"

[build]
  command = "npm run build"
  publish = "out"

# Dodajemy plugin Next.js (bez wersji - Netlify automatycznie użyje najnowszej)
[[plugins]]
  package = "@netlify/plugin-nextjs"