[build.environment]
  NODE_VERSION = "22"
  NETLIFY_USE_YARN = "false"
  NETLIFY_SKIP_BUILD_PLUGINS = "true"

[build]
  command = "npm ci && npm run build"
  publish = "out"

# Próba całkowitego wyłączenia pluginów build